version: '3'
services:
  app:
    container_name: social-media-app
    restart: always
    build: .
    ports:
      - '8080:8000'
    links:
      - mongo
  mongo:
    container_name: mongo_database
    image: mongo
    ports:
      - '39360:39360'